name: TruffleHog-Security-Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  trufflehog_security_scan:
    runs-on: ${{ github.repository_visibility == 'internal' && 'silabs-internal' || 'ubuntu-latest' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.90.3
      with:
        extra_args: --only-verified
